<?php get_header(); ?>

<main class="main-content">
    <div class="container">
        <!-- Page Header -->
        <div class="plans-header">
            <h1>未来计划</h1>
            <p>一起规划我们的美好未来</p>
        </div>

        <!-- Calendar Section -->
        <div class="calendar-section card">
            <h3>日历视图</h3>
            <div class="calendar-container">
                <div class="calendar-header">
                    <button id="prev-month">&lt;</button>
                    <h4 id="current-month"><?php echo date('Y年m月'); ?></h4>
                    <button id="next-month">&gt;</button>
                </div>
                <div class="calendar-grid" id="calendar-grid">
                    <!-- Calendar will be generated by JavaScript -->
                </div>
            </div>
        </div>

        <!-- Main Content Grid -->
        <div class="plans-grid grid grid-2">
            <!-- Goals Section -->
            <div class="goals-section card">
                <div class="section-header">
                    <h3>共同目标</h3>
                    <button class="btn btn-primary" onclick="addGoal()">添加目标</button>
                </div>
                <div class="goals-list">
                    <?php echo get_goals_list(); ?>
                </div>
            </div>

            <!-- Dream Album Section -->
            <div class="dream-album card">
                <div class="section-header">
                    <h3>梦想相册</h3>
                    <button class="btn btn-primary" onclick="addDream()">添加梦想</button>
                </div>
                <div class="dream-photos">
                    <?php echo get_dream_photos(); ?>
                </div>
            </div>
        </div>

        <!-- Upcoming Plans -->
        <div class="upcoming-plans card">
            <h3>即将到来的计划</h3>
            <div class="plans-timeline">
                <?php echo get_upcoming_plans(); ?>
            </div>
        </div>
    </div>

    <!-- Add Goal Modal -->
    <div id="goal-modal" class="modal">
        <div class="modal-content">
            <span class="close">&times;</span>
            <h3>添加新目标</h3>
            <form id="goal-form">
                <div class="form-group">
                    <label>目标标题</label>
                    <input type="text" id="goal-title" placeholder="例如：学游泳" required>
                </div>
                <div class="form-group">
                    <label>目标描述</label>
                    <textarea id="goal-description" placeholder="详细描述这个目标..."></textarea>
                </div>
                <div class="form-group">
                    <label>目标日期</label>
                    <input type="date" id="goal-date" required>
                </div>
                <div class="form-group">
                    <label>当前进度</label>
                    <input type="range" id="goal-progress" min="0" max="100" value="0">
                    <span id="progress-value">0%</span>
                </div>
                <button type="submit" class="btn btn-primary">保存目标</button>
            </form>
        </div>
    </div>

    <!-- Add Dream Modal -->
    <div id="dream-modal" class="modal">
        <div class="modal-content">
            <span class="close">&times;</span>
            <h3>添加梦想照片</h3>
            <form id="dream-form">
                <div class="form-group">
                    <label>梦想图片</label>
                    <input type="file" id="dream-image" accept="image/*">
                </div>
                <div class="form-group">
                    <label>梦想描述</label>
                    <textarea id="dream-description" placeholder="描述这个梦想..." required></textarea>
                </div>
                <div class="form-group">
                    <label>预计实现时间</label>
                    <input type="date" id="dream-date">
                </div>
                <button type="submit" class="btn btn-primary">保存梦想</button>
            </form>
        </div>
    </div>
</main>

<style>
.plans-header {
    text-align: center;
    margin-bottom: 3rem;
    padding: 3rem 0;
    background: var(--gradient-bg);
    color: white;
    border-radius: 20px;
}

.plans-header h1 {
    font-size: 2.5rem;
    margin-bottom: 1rem;
}

.plans-header p {
    font-size: 1.2rem;
    opacity: 0.9;
}

.calendar-section {
    margin-bottom: 2rem;
}

.calendar-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 1rem;
}

.calendar-header button {
    background: var(--primary-color);
    color: white;
    border: none;
    padding: 0.5rem 1rem;
    border-radius: 10px;
    cursor: pointer;
    font-size: 1.2rem;
}

.calendar-grid {
    display: grid;
    grid-template-columns: repeat(7, 1fr);
    gap: 1px;
    background: #eee;
    border-radius: 10px;
    overflow: hidden;
}

.calendar-day {
    background: white;
    padding: 1rem;
    min-height: 80px;
    position: relative;
    cursor: pointer;
    transition: background 0.3s ease;
}

.calendar-day:hover {
    background: #f8f9fa;
}

.calendar-day.other-month {
    color: #ccc;
    background: #f8f9fa;
}

.calendar-day.today {
    background: var(--primary-color);
    color: white;
}

.calendar-day.has-event {
    background: var(--secondary-color);
    color: white;
}

.day-number {
    font-weight: bold;
    margin-bottom: 0.5rem;
}

.day-events {
    font-size: 0.8rem;
}

.plans-grid {
    margin-bottom: 2rem;
}

.section-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 1.5rem;
}

.goals-list {
    space-y: 1rem;
}

.goal-item {
    padding: 1rem;
    border: 2px solid #eee;
    border-radius: 10px;
    margin-bottom: 1rem;
    transition: all 0.3s ease;
}

.goal-item:hover {
    border-color: var(--primary-color);
    transform: translateY(-2px);
}

.goal-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 0.5rem;
}

.goal-title {
    font-weight: bold;
    color: var(--primary-color);
}

.goal-status {
    font-size: 0.9rem;
    color: #666;
}

.goal-progress {
    width: 100%;
    height: 8px;
    background: #eee;
    border-radius: 4px;
    overflow: hidden;
    margin: 0.5rem 0;
}

.goal-progress-bar {
    height: 100%;
    background: var(--accent-color);
    transition: width 0.3s ease;
}

.goal-description {
    font-size: 0.9rem;
    color: #666;
    margin-top: 0.5rem;
}

.dream-photos {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
    gap: 1rem;
}

.dream-item {
    position: relative;
    border-radius: 10px;
    overflow: hidden;
    cursor: pointer;
    transition: transform 0.3s ease;
}

.dream-item:hover {
    transform: scale(1.05);
}

.dream-item img {
    width: 100%;
    height: 120px;
    object-fit: cover;
}

.dream-overlay {
    position: absolute;
    bottom: 0;
    left: 0;
    right: 0;
    background: linear-gradient(transparent, rgba(0,0,0,0.8));
    color: white;
    padding: 1rem 0.5rem 0.5rem;
    font-size: 0.8rem;
}

.plans-timeline {
    position: relative;
}

.timeline-item {
    display: flex;
    align-items: center;
    margin-bottom: 1.5rem;
    padding: 1rem;
    background: #f8f9fa;
    border-radius: 10px;
    border-left: 4px solid var(--primary-color);
}

.timeline-date {
    background: var(--primary-color);
    color: white;
    padding: 0.5rem 1rem;
    border-radius: 20px;
    font-size: 0.9rem;
    margin-right: 1rem;
    white-space: nowrap;
}

.timeline-content {
    flex: 1;
}

.timeline-title {
    font-weight: bold;
    color: var(--text-dark);
    margin-bottom: 0.25rem;
}

.timeline-description {
    color: #666;
    font-size: 0.9rem;
}

.form-group input[type="range"] {
    width: calc(100% - 60px);
    margin-right: 10px;
}

#progress-value {
    font-weight: bold;
    color: var(--primary-color);
}

@media (max-width: 768px) {
    .plans-header h1 {
        font-size: 2rem;
    }
    
    .calendar-day {
        padding: 0.5rem;
        min-height: 60px;
    }
    
    .section-header {
        flex-direction: column;
        gap: 1rem;
        align-items: stretch;
    }
    
    .timeline-item {
        flex-direction: column;
        align-items: flex-start;
    }
    
    .timeline-date {
        margin-bottom: 0.5rem;
        margin-right: 0;
    }
}
</style>

<script>
// Calendar functionality
document.addEventListener('DOMContentLoaded', function() {
    generateCalendar();
    
    document.getElementById('prev-month').addEventListener('click', function() {
        changeMonth(-1);
    });
    
    document.getElementById('next-month').addEventListener('click', function() {
        changeMonth(1);
    });
    
    // Progress range input
    const progressInput = document.getElementById('goal-progress');
    const progressValue = document.getElementById('progress-value');
    
    if (progressInput) {
        progressInput.addEventListener('input', function() {
            progressValue.textContent = this.value + '%';
        });
    }
});

let currentDate = new Date();

function generateCalendar() {
    const year = currentDate.getFullYear();
    const month = currentDate.getMonth();
    
    document.getElementById('current-month').textContent = 
        year + '年' + (month + 1) + '月';
    
    const firstDay = new Date(year, month, 1);
    const lastDay = new Date(year, month + 1, 0);
    const startDate = new Date(firstDay);
    startDate.setDate(startDate.getDate() - firstDay.getDay());
    
    const calendarGrid = document.getElementById('calendar-grid');
    calendarGrid.innerHTML = '';
    
    // Add day headers
    const dayHeaders = ['日', '一', '二', '三', '四', '五', '六'];
    dayHeaders.forEach(day => {
        const dayHeader = document.createElement('div');
        dayHeader.className = 'calendar-day-header';
        dayHeader.textContent = day;
        dayHeader.style.cssText = 'background: var(--primary-color); color: white; text-align: center; padding: 0.5rem; font-weight: bold;';
        calendarGrid.appendChild(dayHeader);
    });
    
    // Generate calendar days
    for (let i = 0; i < 42; i++) {
        const date = new Date(startDate);
        date.setDate(startDate.getDate() + i);
        
        const dayElement = document.createElement('div');
        dayElement.className = 'calendar-day';
        
        if (date.getMonth() !== month) {
            dayElement.classList.add('other-month');
        }
        
        if (date.toDateString() === new Date().toDateString()) {
            dayElement.classList.add('today');
        }
        
        dayElement.innerHTML = `
            <div class="day-number">${date.getDate()}</div>
            <div class="day-events"></div>
        `;
        
        calendarGrid.appendChild(dayElement);
    }
}

function changeMonth(direction) {
    currentDate.setMonth(currentDate.getMonth() + direction);
    generateCalendar();
}

function addGoal() {
    document.getElementById('goal-modal').style.display = 'block';
}

function addDream() {
    document.getElementById('dream-modal').style.display = 'block';
}

// Modal functionality
document.querySelectorAll('.close').forEach(btn => {
    btn.addEventListener('click', function() {
        this.closest('.modal').style.display = 'none';
    });
});

window.addEventListener('click', function(event) {
    if (event.target.classList.contains('modal')) {
        event.target.style.display = 'none';
    }
});

// Form submissions
document.getElementById('goal-form').addEventListener('submit', function(e) {
    e.preventDefault();
    
    const title = document.getElementById('goal-title').value;
    const description = document.getElementById('goal-description').value;
    const date = document.getElementById('goal-date').value;
    const progress = document.getElementById('goal-progress').value;
    
    // Here you would typically send to server
    alert('目标添加成功！');
    document.getElementById('goal-modal').style.display = 'none';
    this.reset();
    document.getElementById('progress-value').textContent = '0%';
});

document.getElementById('dream-form').addEventListener('submit', function(e) {
    e.preventDefault();
    
    const description = document.getElementById('dream-description').value;
    const date = document.getElementById('dream-date').value;
    
    // Here you would typically send to server
    alert('梦想添加成功！');
    document.getElementById('dream-modal').style.display = 'none';
    this.reset();
});
</script>

<?php get_footer(); ?>

<?php
// Functions for future plans page

function get_goals_list() {
    global $wpdb;
    $table = $wpdb->prefix . 'heartbeat_plans';
    $goals = $wpdb->get_results("SELECT * FROM $table ORDER BY target_date ASC", ARRAY_A);
    
    $output = '';
    
    if (empty($goals)) {
        // Sample goals
        $sample_goals = array(
            array('title' => '学游泳', 'description' => '一起学会游泳，享受水中的乐趣', 'progress' => 30, 'target_date' => '2024-12-31'),
            array('title' => '跨年旅行', 'description' => '计划一次浪漫的跨年旅行', 'progress' => 60, 'target_date' => '2024-12-31'),
            array('title' => '新年计划', 'description' => '制定新一年的共同目标', 'progress' => 10, 'target_date' => '2025-01-01')
        );
        
        foreach ($sample_goals as $goal) {
            $formatted_date = date('Y年m月d日', strtotime($goal['target_date']));
            $output .= "<div class='goal-item'>";
            $output .= "<div class='goal-header'>";
            $output .= "<div class='goal-title'>{$goal['title']}</div>";
            $output .= "<div class='goal-status'>目标日期: $formatted_date</div>";
            $output .= "</div>";
            $output .= "<div class='goal-progress'>";
            $output .= "<div class='goal-progress-bar' style='width: {$goal['progress']}%'></div>";
            $output .= "</div>";
            $output .= "<div class='goal-description'>{$goal['description']}</div>";
            $output .= "</div>";
        }
    } else {
        foreach ($goals as $goal) {
            $formatted_date = date('Y年m月d日', strtotime($goal['target_date']));
            $output .= "<div class='goal-item'>";
            $output .= "<div class='goal-header'>";
            $output .= "<div class='goal-title'>" . esc_html($goal['plan_title']) . "</div>";
            $output .= "<div class='goal-status'>目标日期: $formatted_date</div>";
            $output .= "</div>";
            $output .= "<div class='goal-progress'>";
            $output .= "<div class='goal-progress-bar' style='width: {$goal['progress']}%'></div>";
            $output .= "</div>";
            $output .= "<div class='goal-description'>" . esc_html($goal['plan_description']) . "</div>";
            $output .= "</div>";
        }
    }
    
    return $output;
}

function get_dream_photos() {
    // Sample dream photos
    $dreams = array(
        array('image' => 'https://via.placeholder.com/200x150/ff6b9d/ffffff?text=Travel', 'description' => '环游世界'),
        array('image' => 'https://via.placeholder.com/200x150/4ecdc4/ffffff?text=House', 'description' => '温馨小屋'),
        array('image' => 'https://via.placeholder.com/200x150/45b7d1/ffffff?text=Wedding', 'description' => '完美婚礼')
    );
    
    $output = '';
    foreach ($dreams as $dream) {
        $output .= "<div class='dream-item'>";
        $output .= "<img src='{$dream['image']}' alt='{$dream['description']}' />";
        $output .= "<div class='dream-overlay'>{$dream['description']}</div>";
        $output .= "</div>";
    }
    
    return $output;
}

function get_upcoming_plans() {
    global $wpdb;
    $table = $wpdb->prefix . 'heartbeat_plans';
    $plans = $wpdb->get_results("SELECT * FROM $table WHERE target_date >= CURDATE() ORDER BY target_date ASC LIMIT 5", ARRAY_A);
    
    $output = '';
    
    if (empty($plans)) {
        // Sample upcoming plans
        $sample_plans = array(
            array('title' => '周末约会', 'description' => '去新开的咖啡厅', 'date' => date('Y-m-d', strtotime('+3 days'))),
            array('title' => '月度纪念日', 'description' => '庆祝我们在一起的每一个月', 'date' => date('Y-m-d', strtotime('+10 days'))),
            array('title' => '看电影', 'description' => '一起看期待已久的新电影', 'date' => date('Y-m-d', strtotime('+15 days')))
        );
        
        foreach ($sample_plans as $plan) {
            $formatted_date = date('m月d日', strtotime($plan['date']));
            $output .= "<div class='timeline-item'>";
            $output .= "<div class='timeline-date'>$formatted_date</div>";
            $output .= "<div class='timeline-content'>";
            $output .= "<div class='timeline-title'>{$plan['title']}</div>";
            $output .= "<div class='timeline-description'>{$plan['description']}</div>";
            $output .= "</div>";
            $output .= "</div>";
        }
    } else {
        foreach ($plans as $plan) {
            $formatted_date = date('m月d日', strtotime($plan['target_date']));
            $output .= "<div class='timeline-item'>";
            $output .= "<div class='timeline-date'>$formatted_date</div>";
            $output .= "<div class='timeline-content'>";
            $output .= "<div class='timeline-title'>" . esc_html($plan['plan_title']) . "</div>";
            $output .= "<div class='timeline-description'>" . esc_html($plan['plan_description']) . "</div>";
            $output .= "</div>";
            $output .= "</div>";
        }
    }
    
    return $output ?: '<p>暂无即将到来的计划</p>';
}
?>
