version: '3.9'

services:
  mariadb:
    image: mariadb:11
    container_name: heartbeat-mariadb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_DATABASE: heartbeat
      MARIADB_USER: heartbeat
      MARIADB_PASSWORD: heartbeat
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  mariadb-data:
